/*
 Navicat Premium Data Transfer

 Source Server         : 127.0.0.1
 Source Server Type    : MySQL
 Source Server Version : 50710
 Source Host           : 127.0.0.1
 Source Database       : DW_MetaData

 Target Server Type    : MySQL
 Target Server Version : 50710
 File Encoding         : utf-8

 Date: 02/01/2016 15:53:40 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `AL_DataSource`
-- ----------------------------
DROP TABLE IF EXISTS `AL_DataSource`;
CREATE TABLE `AL_DataSource` (
  `RecordID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `TargetSourceDBName` varchar(32) NOT NULL COMMENT '目标数据库的名称，必须填写mysql之类的数据库名称\r目标数据库的名称，必须填写mysql之类的数据库名称\r目标数据库的名称，必须填写mysql之类的数据库名称',
  `Name` varchar(32) NOT NULL COMMENT '名称，可随意填写',
  `Url` varchar(256) DEFAULT NULL COMMENT '连接字符串',
  `UserName` varchar(64) DEFAULT NULL COMMENT '用户名',
  `Password` varchar(64) DEFAULT NULL COMMENT '密码',
  `Enable` tinyint(1) DEFAULT NULL COMMENT '是否可用，0表示不可用，1表示可用',
  `MTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RecordID`),
  UNIQUE KEY `IDX_NAME` (`TargetSourceDBName`,`Name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='说明：\n	目前仅支持mysql数据库，TargetSourceDBName一定要填mysql';

-- ----------------------------
--  Records of `AL_DataSource`
-- ----------------------------
BEGIN;
INSERT INTO `AL_DataSource` VALUES ('1', 'mysql', 'default', 'jdbc:mysql://127.0.0.1:3306/test', 'root', 'root', '1', '2016-01-15 17:05:35', '2016-01-29 15:51:53'), ('2', 'csv', 'csv', null, null, null, '1', '2016-01-26 11:55:42', '2016-01-29 15:51:53');
COMMIT;

-- ----------------------------
--  Table structure for `AL_InputFile`
-- ----------------------------
DROP TABLE IF EXISTS `AL_InputFile`;
CREATE TABLE `AL_InputFile` (
  `RecordID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `GroupID` bigint(20) DEFAULT NULL COMMENT '组ID，关联AL_InputGroup表',
  `DataSourceID` bigint(20) DEFAULT NULL COMMENT '数据源ID，关联AL_DataSource表',
  `FileName` varchar(45) DEFAULT NULL COMMENT '名称，可随意填写，此Name不是需要导入文件的Name',
  `FilePath` varchar(200) DEFAULT NULL COMMENT '导入的文件路径',
  `FileRegExp` varchar(200) DEFAULT NULL COMMENT '导入的文件名的正则表达式，匹配该正则的文件都会被扫描到',
  `FileSeparator` varchar(20) DEFAULT '	' COMMENT '文件分隔符',
  `InputSql` text COMMENT '配置INSERT语句，如：INSERT INTO HYY_TB(Name,#UP#=Age) Values({1},{2})；其中{1},{2}表示读取文件的第1个和第2个字段，如果字段中配置了#UP#=，那么会自动生成ON DUPLICATE KEY语句，对应update配置#UP#的字段',
  `Sort` int(11) DEFAULT NULL COMMENT '扫描导入文件的顺序，从小到大',
  `Enable` int(9) DEFAULT '1' COMMENT '是否可用，0表示不可用，1表示可用',
  `MTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RecordID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COMMENT='说明：\n	这是最核心与最重要的一个配置文件，一条配置信息，通常是将一个路径下的一组被正则表达式匹配的csv文件导入到一个Mysql表中，你还可以配置文件的分隔符与扫描的顺序等等，文件名中常常包含周期与日期的固定维度，你可以在配置表AL_InputFileConstant中获取你得周期与日期并且定义任意个占位（如：{PeriodKey}），并填入到该配置的InputSql中。\n	有一种常见情况，就是你重新又生成了一次该csv，这种情况我们叫做重复导入，针对重要的情况，你可以根据文件名中体现出来的周期与日期维度将该数据删除，然后再导入mysql中，删除数据的那一步在配置表AL_InputFileBefore中配置，在导入每一个csv之前，都会执行一下delete sql。【当然，你对程序足够自信的话，也可以使用Mysql自带的特性ON DUPLICATE KEY，详情见InputSql的注释。】\n	当你的csv中包含维度信息的时候，你需要在AL_InputFileField配置表中配置，DimFlag必须设置成1（表示该维度会被导入到mysql），支持多重维度（维度中包含维度）配置，你配置维度后，通常会在AL_InputFileField表中的FieldPointName中自定义一个名称（如：{ProductID}），在InputSql中{ProductID}会自动被替换成该维度表的主键ID（配置在AL_InputFileField表中的DimValue）\n	当你的csv中字段需要做一些常规处理的时候，你需要在AL_InputFileField配置表中配置，在Dim开头的字段都不需要配置，设置成Null即可。\n	当程序处理的日志，通常会被记录到AL_InputFileLog表中。\n注意：\n	AL_InputFileConstant和AL_InputFileField配置表大同小异，前者大多用于抓取文件名中的内容，后者大多用于转换文件中的内容以及维度信息。';

-- ----------------------------
--  Records of `AL_InputFile`
-- ----------------------------
BEGIN;
INSERT INTO `AL_InputFile` VALUES ('1', '1', null, 'hyy', '/Users/hyy/Work/data', 'hyy.csv', '\\t', 'insert into hyy values({1},{2})', '1', '0', '2016-01-28 15:21:39', null), ('2', '1', '2', 'hyy', '/Users/hyy/Work/data', 'hyy.csv', '\\t', '{1}\\t{2}\\t{3}', '2', '0', '2016-01-28 15:21:43', null), ('10', '1', null, '案例一事实一', '/Users/hyy/Work/data', 'fact_sales_\\d*_\\d*.csv', '\\t', 'INSERT INTO Fact_Sales(PeriodKey,DayKey,ProductID,SalesmanID,SpotPriceTotal,SalePriceTotal) VALUES({PeriodKey},{DayKey},{ProductID},{SalesmanID},{4},{5})', '3', '1', '2016-01-29 18:25:06', null);
COMMIT;

-- ----------------------------
--  Table structure for `AL_InputFileBefore`
-- ----------------------------
DROP TABLE IF EXISTS `AL_InputFileBefore`;
CREATE TABLE `AL_InputFileBefore` (
  `RecordID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `FileID` bigint(20) DEFAULT NULL COMMENT '关联表AL_InputFile',
  `DataSourceID` bigint(20) DEFAULT NULL COMMENT '关联表AL_DataSource',
  `BeforeSql` text COMMENT '在导入每个文件时，需要执行的SQL语句，可以配置成如：delete from table where PeriodKey={PeriodKey} and DayKey={DayKey}，这些占位字段需要在AL_InputFileConstant中配置',
  `Sort` int(9) DEFAULT NULL COMMENT '执行顺序，从小到大',
  `Enable` int(9) DEFAULT '1' COMMENT '是否可用，0表示不可用，1表示可用',
  `MTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RecordID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='说明：\n	该表配置导入每个文件时，可以先执行的一条SQL语句，有一种常见情况，就是你重新又生成了一次该csv，这种情况我们叫做重复导入，针对重要的情况，你可以根据文件名中体现出来的周期与日期维度将该数据删除，然后再导入mysql中，删除数据的那一步在这里配置，在导入每一个csv之前，都会执行一下delete sql。当然，你也可以不这么做。';

-- ----------------------------
--  Records of `AL_InputFileBefore`
-- ----------------------------
BEGIN;
INSERT INTO `AL_InputFileBefore` VALUES ('1', '10', null, 'delete from Fact_Sales where PeriodKey={PeriodKey} and DayKey={DayKey}', '1', '1', '2016-01-29 18:24:13', '2016-01-29 18:17:08');
COMMIT;

-- ----------------------------
--  Table structure for `AL_InputFileConstant`
-- ----------------------------
DROP TABLE IF EXISTS `AL_InputFileConstant`;
CREATE TABLE `AL_InputFileConstant` (
  `RecordID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `FileID` bigint(20) DEFAULT NULL COMMENT '关联表AL_InputFile。',
  `FieldPointName` varchar(128) DEFAULT NULL COMMENT '对应的SQL占位符，格式：{PeriodKey}，{DayKey}',
  `DefaultValue` varchar(32) DEFAULT NULL COMMENT '当读取到该值为空字符串时的默认值，系统保留占位：#NULL_STR#表示null字符串，#EMPTY#表示空字符串，#NULL#表示数据库中的Null值',
  `ConvertMethod` varchar(64) DEFAULT NULL COMMENT '转换的方法，可以将值转成大写或小写，配置lower或者upper',
  `OldFormat` varchar(256) DEFAULT NULL COMMENT '正则表达式转换，如果配置fact_sales_(\\d*)_(\\d*).csv，需要注意的是，括号中的，是正则抓取的内容，在这里抓取到了一组值，这组值要被输出成什么格式，需要在NewFormat中配置。',
  `NewFormat` varchar(256) DEFAULT NULL COMMENT '通过OldFormat正则表达式抓取出的一组值，配置{n}表示获得第n个值，配置{.}回将所有抓出来的值都连接起来，你也可以在配置中加入任意字符串，如加入下划线：{1}_{2}_{3}',
  `LimitLength` varchar(16) DEFAULT NULL COMMENT '如果字符串太长，你可以通过此配置截断字符串，配置一：[1,100]即是截取1到100个；配置二：[50,]即是截取从第50个到最后；配置三：[,50]即是截取最后50个',
  `Sort` int(11) DEFAULT NULL COMMENT '转换顺序，从小到大',
  `MTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RecordID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='说明：\n	AL_InputFileConstant和AL_InputFileField配置表大同小异，前者大多用于抓取文件名中的内容，后者大多用于转换文件中的内容以及维度信息。\n	系统占位#FILENAME#和#FILEPATH#可分别读取当前的路径与文件名，配置到DefaultValue中即可。然后自定义FieldPointName（如：{DayKey}），则可在配置表AL_InputFile或者AL_InputFileFields或者AL_InputFileBefor中填写{DayKey}';

-- ----------------------------
--  Records of `AL_InputFileConstant`
-- ----------------------------
BEGIN;
INSERT INTO `AL_InputFileConstant` VALUES ('1', '10', '{PeriodKey}', '#FILENAME#', null, 'fact_sales_(\\d*)_\\d*.csv', '{1}', null, null, '2016-01-28 16:36:40', '2016-01-29 15:50:16'), ('2', '10', '{DayKey}', '#FILENAME#', null, 'fact_sales_\\d*_(\\d*).csv', '{1}', null, null, '2016-01-28 16:42:45', '2016-01-29 15:50:16');
COMMIT;

-- ----------------------------
--  Table structure for `AL_InputFileField`
-- ----------------------------
DROP TABLE IF EXISTS `AL_InputFileField`;
CREATE TABLE `AL_InputFileField` (
  `RecordID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `FileID` bigint(20) DEFAULT NULL COMMENT '关联表AL_InputFile',
  `DataSourceID` bigint(20) DEFAULT NULL COMMENT '关联表AL_DataSource',
  `FieldPointName` varchar(20) DEFAULT NULL COMMENT '对应的SQL占位符，格式：{ProductID}，{SalesmanID}',
  `DimFlag` int(9) DEFAULT '0' COMMENT '设置成1，表示该维度会被导入到mysql',
  `DimTableName` varchar(100) DEFAULT NULL COMMENT '维度表名',
  `DimKey` varchar(256) DEFAULT NULL COMMENT '该Key并非维度表的Key，一般表示维度名称，因为维度名称不可能相同',
  `DimValue` varchar(256) DEFAULT NULL COMMENT '该Value表示维度表的主键ID',
  `DefaultValue` varchar(256) DEFAULT NULL COMMENT '当读取到该值为空字符串时的默认值，系统保留占位：#NULL_STR#表示null字符串，#EMPTY#表示空字符串，#NULL#表示数据库中的Null值',
  `ConvertMethod` varchar(256) DEFAULT NULL COMMENT '转换的方法，可以将值转成大写或小写，配置lower或者upper',
  `OldFormat` varchar(256) DEFAULT NULL COMMENT '正则表达式转换，如果配置fact_sales_(\\d*)_(\\d*).csv，需要注意的是，括号中的，是正则抓取的内容，在这里抓取到了一组值，这组值要被输出成什么格式，需要在NewFormat中配置。',
  `NewFormat` varchar(256) DEFAULT NULL COMMENT '通过OldFormat正则表达式抓取出的一组值，配置{n}表示获得第n个值，配置{.}回将所有抓出来的值都连接起来，你也可以在配置中加入任意字符串，如加入下划线：{1}_{2}_{3}',
  `LimitLength` varchar(20) DEFAULT NULL COMMENT '如果字符串太长，你可以通过此配置截断字符串，配置一：[1,100]即是截取1到100个；配置二：[50,]即是截取从第50个到最后；配置三：[,50]即是截取最后50个',
  `Sort` int(11) DEFAULT NULL COMMENT '转换顺序，从小到大',
  `MTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RecordID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='说明：\n	AL_InputFileConstant和AL_InputFileField配置表大同小异，前者大多用于抓取文件名中的内容，后者大多用于转换文件中的内容以及维度信息。\n	当你的csv中包含维度信息的时候，你需要在AL_InputFileField配置表中配置，DimFlag必须设置成1（表示该维度会被导入到mysql），支持多重维度（维度中包含维度）配置，你配置维度后，通常会在AL_InputFileField表中的FieldPointName中自定义一个名称（如：{ProductID}），在AL_InputFile的InputSql中{ProductID}会自动被替换成该维度表的主键ID（配置在AL_InputFileField表中的DimValue）\n	当你的csv中字段需要做一些常规处理的时候，你需要在AL_InputFileField配置表中配置，在Dim开头的字段都不需要配置，设置成Null即可。';

-- ----------------------------
--  Records of `AL_InputFileField`
-- ----------------------------
BEGIN;
INSERT INTO `AL_InputFileField` VALUES ('1', '10', null, '{SalesmanID}', '1', 'Dim_Salesman', 'SalesmanName:{3}', 'RecordID', null, null, null, null, null, '1', '2016-01-28 16:45:29', '2016-01-28 15:18:38'), ('2', '10', null, '{ProductLevelID}', '1', 'Dim_Product_Level', 'ProductLevelName:{1}', 'RecordID', null, null, null, null, null, '2', '2016-01-28 16:45:42', '2016-01-28 15:06:24'), ('3', '10', null, '{ProductID}', '1', 'Dim_Product', 'ProductName:{2},ProductLevelID:{ProductLevelID}', 'RecordID', null, null, null, null, null, '3', '2016-01-28 16:46:04', '2016-01-28 15:15:17');
COMMIT;

-- ----------------------------
--  Table structure for `AL_InputFileLog`
-- ----------------------------
DROP TABLE IF EXISTS `AL_InputFileLog`;
CREATE TABLE `AL_InputFileLog` (
  `RecordID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `GroupID` bigint(20) DEFAULT NULL COMMENT '关联表AL_InputGroup',
  `FileID` bigint(20) DEFAULT NULL COMMENT '关联表AL_InputFile',
  `RealFilePath` varchar(256) DEFAULT NULL COMMENT '真实的文件路径',
  `RealFileName` varchar(128) DEFAULT NULL COMMENT '真实的文件名',
  `Result` varchar(16) DEFAULT NULL COMMENT '执行结果，0.fail | 1.success',
  `Detail` text COMMENT '日志详情，错误信息',
  `IsRead` tinyint(1) DEFAULT '0' COMMENT '是否已读，默认0是未读',
  `MTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RecordID`),
  KEY `IDX_UL_SARUUC` (`CTime`) USING BTREE,
  KEY `IDX_GroupID` (`GroupID`),
  KEY `IDX_FileID` (`FileID`),
  KEY `IDX_RealFilePath` (`RealFilePath`),
  KEY `IDX_RealFileName` (`RealFileName`),
  KEY `IDX_Result` (`Result`),
  KEY `IDX_IsRead` (`IsRead`)
) ENGINE=InnoDB AUTO_INCREMENT=138 DEFAULT CHARSET=utf8 COMMENT='说明：\n	这是一个日志记录表，非常单纯。需要在/Auto/resource/sys-config.properties中配置database.log.success.flag=true和database.log.fail.flag=true，才会将记录插入到该表中，一般默认是开启的。';

-- ----------------------------
--  Records of `AL_InputFileLog`
-- ----------------------------
BEGIN;
INSERT INTO `AL_InputFileLog` VALUES ('1', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-15 17:23:29'), ('2', '1', '1', null, null, 'fail', 'org.blazer.dataload.exception.DirectoryNotFoundException: /home/www/hyy/data/ is not directory\r\n    at org.blazer.dataload.util.FileUtil.findFileNameRegexp(FileUtil.java:194)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:198)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-15 18:37:12'), ('3', '1', '1', null, null, 'fail', 'org.blazer.dataload.exception.DirectoryNotFoundException: /home/www/hyy/data/ is not directory\r\n    at org.blazer.dataload.util.FileUtil.findFileNameRegexp(FileUtil.java:194)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:198)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-25 18:00:01'), ('4', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:347)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-25 18:00:46'), ('5', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-25 18:01:23'), ('6', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:347)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-25 19:35:51'), ('7', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:347)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-25 19:46:18'), ('8', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:347)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-25 19:47:41'), ('9', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:347)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-26 09:57:50'), ('10', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:347)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-26 10:06:36'), ('11', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:347)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:77)', '0', '2016-01-29 15:50:59', '2016-01-26 10:21:57'), ('12', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 11:32:38'), ('13', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 11:40:48'), ('14', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 11:42:22'), ('15', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 11:44:43'), ('16', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 11:51:56'), ('17', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 11:56:56'), ('18', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 11:57:58'), ('19', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 12:02:07'), ('20', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 12:03:37'), ('21', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 12:03:37'), ('22', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\');]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:673)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:22:01'), ('23', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 20:22:01'), ('24', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:35:17'), ('25', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 20:35:17'), ('26', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:35:57'), ('27', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 20:35:57'), ('28', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:37:26'), ('29', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 20:37:26'), ('30', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:44:25'), ('31', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'java.lang.NullPointerException\r\n    at java.lang.String.replace(String.java:2240)\r\n    at org.blazer.dataload.service.ALService.setConvertSqlsByCsv(ALService.java:271)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:330)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:44:25'), ('32', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:48:17'), ('33', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'java.lang.NullPointerException\r\n    at java.lang.String.replace(String.java:2240)\r\n    at org.blazer.dataload.service.ALService.setConvertSqlsByCsv(ALService.java:271)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:330)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:48:56'), ('34', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:49:06'), ('35', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:56:06'), ('36', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 20:58:45'), ('37', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:01:03'), ('38', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:01:03'), ('39', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:01:20'), ('40', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:01:20'), ('41', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:04:39'), ('42', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:04:39'), ('43', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:05:12'), ('44', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:05:12'), ('45', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:05:29'), ('46', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:05:29'), ('47', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:05:47'), ('48', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:05:47'), ('49', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:06:29'), ('50', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:06:29'), ('51', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:10:25'), ('52', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:10:25'), ('53', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-26 21:11:02'), ('54', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-26 21:11:02'), ('55', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-27 10:25:09'), ('56', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-27 10:25:09'), ('57', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-27 10:25:45'), ('58', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-27 10:25:45'), ('59', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-27 10:25:54'), ('60', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-27 10:25:54'), ('61', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-27 10:26:02'), ('62', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-27 10:26:02'), ('63', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:676)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-27 10:29:04'), ('64', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-27 10:29:04'), ('65', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:675)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-27 10:30:27'), ('66', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-27 10:30:27'), ('67', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:675)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 11:41:53'), ('68', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 11:41:53'), ('69', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:675)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 11:59:56'), ('70', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 11:59:56'), ('71', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:675)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 13:56:07'), ('72', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:675)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 13:56:07'), ('73', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 13:56:07'), ('74', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:00:32'), ('75', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:00:32'), ('76', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:00:32'), ('77', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:04:04'), ('78', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:04:04'), ('79', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:04:04'), ('80', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:05:29'), ('81', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:05:29'), ('82', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:05:29'), ('83', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:08:22'), ('84', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:348)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:08:22'), ('85', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:08:22'), ('86', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:14:22'), ('87', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:14:22'), ('88', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:14:22'), ('89', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:351)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:18:17');
INSERT INTO `AL_InputFileLog` VALUES ('90', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:351)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:18:17'), ('91', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:18:17'), ('92', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:20:40'), ('93', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:20:40'), ('94', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:20:40'), ('95', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:35:46'), ('96', '1', '8', '/Users/hyy/Work/data/', 'dim_salesman_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Dim_Salesman(SalesmanName) VALUES({salesman})]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertDim(ALService.java:732)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:319)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:35:46'), ('97', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:35:46'), ('98', '1', '9', null, null, 'fail', 'java.lang.NullPointerException\r\n    at java.util.regex.Pattern.<init>(Pattern.java:1350)\r\n    at java.util.regex.Pattern.compile(Pattern.java:1028)\r\n    at org.blazer.dataload.util.FileUtil.findFileNameRegexp(FileUtil.java:196)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:201)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:35:46'), ('99', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:35:46'), ('100', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:42:47'), ('101', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:45:41'), ('102', '1', '8', '/Users/hyy/Work/data/', 'dim_salesman_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:45:41'), ('103', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:45:41'), ('104', '1', '9', null, null, 'fail', 'java.lang.NullPointerException\r\n    at java.util.regex.Pattern.<init>(Pattern.java:1350)\r\n    at java.util.regex.Pattern.compile(Pattern.java:1028)\r\n    at org.blazer.dataload.util.FileUtil.findFileNameRegexp(FileUtil.java:196)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:201)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:45:41'), ('105', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:45:41'), ('106', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:49:55'), ('107', '1', '8', '/Users/hyy/Work/data/', 'dim_salesman_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:49:55'), ('108', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 14:49:55'), ('109', '1', '9', null, null, 'fail', 'java.lang.NullPointerException\r\n    at java.util.regex.Pattern.<init>(Pattern.java:1350)\r\n    at java.util.regex.Pattern.compile(Pattern.java:1028)\r\n    at org.blazer.dataload.util.FileUtil.findFileNameRegexp(FileUtil.java:196)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:201)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:49:55'), ('110', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 14:49:55'), ('111', '1', '1', '/Users/hyy/Work/data/', 'hyy.csv', 'fail', 'org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into hyy values(\'1\',\'aaa\')]; Duplicate entry \'1\' for key \'PRIMARY\'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry \'1\' for key \'PRIMARY\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:21'), ('112', '1', '8', '/Users/hyy/Work/data/', 'dim_salesman_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:21'), ('113', '1', '2', '/Users/hyy/Work/data/', 'hyy.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:21'), ('114', '1', '9', '/Users/hyy/Work/data/', 'dim_product_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:21'), ('115', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:21'), ('116', '1', '8', '/Users/hyy/Work/data/', 'dim_salesman_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:50'), ('117', '1', '9', '/Users/hyy/Work/data/', 'dim_product_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:50'), ('118', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 15:21:50'), ('119', '1', '8', '/Users/hyy/Work/data/', 'dim_salesman_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 15:26:29'), ('120', '1', '9', '/Users/hyy/Work/data/', 'dim_product_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 15:26:29'), ('121', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'MacPro\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:679)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 15:26:29'), ('122', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'一级\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:680)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 16:24:29'), ('123', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales VALUES(\'一级\')]; nested exception is java.sql.SQLException: Column count doesn\'t match value count at row 1\r\n    at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:680)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 16:25:34'), ('124', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales(PeriodKey,DayKey,ProductID,SakesmanID,SpotPriceTotal,SalePriceTotal) VALUES(\'1\',\'20160128\',{ProductID},{SalesmanID},\'120000\',\'160000\')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \',\'120000\',\'160000\')\' at line 1\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:680)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 16:43:22'), ('125', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO Fact_Sales(PeriodKey,DayKey,ProductID,SakesmanID,SpotPriceTotal,SalePriceTotal) VALUES(\'1\',\'20160128\',\'1\',\'1\',\'120000\',\'160000\')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column \'SakesmanID\' in \'field list\'\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputFile(ALService.java:680)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:352)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:78)', '0', '2016-01-29 15:50:59', '2016-01-28 16:46:18'), ('126', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 16:47:15'), ('127', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-28 16:48:03'), ('128', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-29 13:25:49'), ('129', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-29 13:29:04'), ('130', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-29 13:30:19'), ('131', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-29 13:33:11'), ('132', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-29 13:35:27'), ('133', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 15:50:59', '2016-01-29 13:38:28'), ('134', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [delete from table Fact_Sales]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'table Fact_Sales\' at line 1\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputBefore(ALService.java:769)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:349)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:79)', '0', '2016-01-29 18:21:05', '2016-01-29 18:21:05'), ('135', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'fail', 'org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [delete from table Fact_Sales where PeriodKey=\'1\' and DayKey=\'20160128\']; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'table Fact_Sales where PeriodKey=\'1\' and DayKey=\'20160128\'\' at line 1\r\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)\r\n    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\r\n    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)\r\n    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:519)\r\n    at org.blazer.common.dao.TransactionDao.batchUpdate(TransactionDao.java:132)\r\n    at org.blazer.dataload.service.ALService.insertInputBefore(ALService.java:769)\r\n    at org.blazer.dataload.handle.ALHandle.handle(ALHandle.java:349)\r\n    at org.blazer.dataload.handle.ALHandle.main(ALHandle.java:79)', '0', '2016-01-29 18:23:30', '2016-01-29 18:23:30'), ('136', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 18:24:17', '2016-01-29 18:24:17'), ('137', '1', '10', '/Users/hyy/Work/data/', 'fact_sales_1_20160128.csv', 'success', '', '0', '2016-01-29 18:25:11', '2016-01-29 18:25:11');
COMMIT;

-- ----------------------------
--  Table structure for `AL_InputGroup`
-- ----------------------------
DROP TABLE IF EXISTS `AL_InputGroup`;
CREATE TABLE `AL_InputGroup` (
  `RecordID` bigint(20) NOT NULL COMMENT '记录ID',
  `DataSourceID` bigint(20) DEFAULT NULL COMMENT '关联表AL_DataSource',
  `GroupName` varchar(45) DEFAULT NULL COMMENT '名称，随意填写',
  `Enable` int(9) DEFAULT NULL COMMENT '是否可用，0表示不可用，1表示可用',
  `MTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RecordID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='说明：\n	该表也很单纯，就是为了将AL_InputFile分组，需要引用该表RecordID，你懂得。';

-- ----------------------------
--  Records of `AL_InputGroup`
-- ----------------------------
BEGIN;
INSERT INTO `AL_InputGroup` VALUES ('1', '1', '何云洋', '1', '2016-01-15 17:04:26', null);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
